# This is a basic workflow to help you get started with Actions

name: xcodebuild

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out Code
        uses: actions/checkout@v2
      
      - name: Import Certificate
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.SIGNING_CERTIFICATE_ASPATIAL_P12 }}
          p12-password: ${{ secrets.SIGNING_CERTIFICATE_ASPATIAL_P12_PASSWORD }}

      - name: Build File
        id: build_file
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: Matrix-ScreenSaver.xcodeproj
          scheme: Matrix-ScreenSaver
          derived-data-path: build
          destination: platform=macOS
          action: build
          
      - name: Zip File
        run: |
          ls /Users/runner/work/Matrix-ScreenSaver/Matrix-ScreenSaver/build
      # ls /Users/runner/work/Matrix-ScreenSaver/Matrix-ScreenSaver/build
      # zip -r ./Release/Matrix-ScreenSaver.zip ./Release/Matrix-ScreenSaver.saver
          
          
